# Generated by Django 3.2.18 on 2023-05-01 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommend', '0004_alter_resume_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
